import Vue from 'vue'
import Router from 'vue-router'

Vue.use(Router)

export default new Router({
  routes:[
    {
      path:'/',
      redirect:'/dashboard'
    },
    {
      path:'/',
      component:resolve=>require(['../components/common/Home.vue'],resolve),
      meta: {  title:"自述文件"},
      children:[
        {
          path:'/dashboard',
          component:resolve=>require(['../components/page/Dashboard.vue'],resolve),
          meta:{title:'系统首页'}
        },
        {
          path:'/table',
          component:resolve=>require(['../components/page/Table.vue'],resolve),
          meta:{title:'基础表格'}
        },
        {
          path:'/tabs',
          component:resolve=>require(['../components/page/Tabs.vue'],resolve),
          meta:{title:'tab选项卡'}
        },
        {
          path:'/form',
          component:resolve=>require(['../components/page/BaseForm.vue'],resolve),
          meta:{title:'基本表单'}
        },
        {
          path:'/editor',
          component:resolve=>require(['../components/page/Editor.vue'],resolve),
          meta:{title:'富文本编辑'}
        },
        {
          path:'/markdown',
          component:resolve=>require(['../components/page/Markdown.vue'],resolve),
          meta:{title:'markdown编辑器'}
        },
        {
          path:'/upload',
          component:resolve=>require(['../components/page/Upload.vue'],resolve),
          meta:{title:'文件上传'}
        },
        {
          path:'/charts',
          component:resolve=>require(['../components/page/sCharts.vue'],resolve),
          meta:{title:'schart图标'}
        },
        {
          path:'/drag',
          component:resolve=>require(['../components/page/DragList.vue'],resolve),
          meta:{title:'拖拽列表'}
        },
        {
          path:'/permission',
          component:resolve=>require(['../components/page/Permission.vue'],resolve),
          meta:{title:'权限测试'}
        }
      ]
    },
    {
      path:'/login',
      component:resolve=>require(['../components/page/Login.vue'],resolve)
    }
  ]
})
